apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    # Forces MetalLB to assign this specific IP address
    metallb.universe.tf/loadBalancerIPs: 10.0.0.210
spec:
  type: LoadBalancer
